### ISSUE TITLE
What is the minimum iOS version supported by each version?

### ISSUE THREAD

**Issue by tangguoEddy** [NordicSemiconductor/IOS-DFU-Library#523]
My Xcode is version 15.0.1 (15A507), and I would like the minimum deployment target to be iOS 11. I find it strange that you declare a minimum support of iOS 9 in package.swift, but I am getting the following compilation errors:
```
Compiling for iOS 11.0, but module 'NordicDFU' has a minimum deployment target of iOS 12.0: /Users/eddy
```

**Comment by philips77** [comment]
Please use version (tag) 4.13.0.

I'm working on 4.14, with no changes in the library other than documentation, which will increase min iOS to 12 due to the new Xcode requirements. This is the minimum version it compiles now, and we can't push to CocoaPods with 8 or 11.
But min iOS version for 4.13 is iOS 9.
